INSERT INTO user(`birthday`, `email`, `genre`, `lastname`, `name`, `password`, `enabled`, `token_expired`) VALUES('1987-09-18', 'super_rodmontiel@rodmontiel.com', '1', 'Montiel', 'Rodrigo', '$2a$10$3qxcbpqeQtSk2dFSuGHwquncewait5aSZP0fqI3hGRBMas/HaKAXO', 1, 1)
INSERT INTO role(`name`) VALUES('ADMIN')
INSERT INTO role(`name`) VALUES('USER')
INSERT INTO user_role(`user_id`,`role_id`) VALUES(1,1)
INSERT INTO privilege(`name`) VALUES('ALL')
INSERT INTO privilege(`name`) VALUES('EXPENSES')
INSERT INTO role_privilege(`role_id`, `privilege_id`) VALUES(1,1)
INSERT INTO role_privilege(`role_id`, `privilege_id`) VALUES(2,2)